import { GroceryItem, GroceryList } from '../types';

export const INITIAL_LISTS: GroceryList[] = [
  {
    id: 'list_supermarket',
    name: 'Supermarket',
    description: 'Weekly grocery run & fresh staples',
    icon: 'shopping-cart',
    color: 'emerald',
    isDefault: true,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'list_costco',
    name: 'Costco',
    description: 'Bulk household essentials & snacks',
    icon: 'box',
    color: 'amber',
    isDefault: false,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'list_pharmacy',
    name: 'Pharmacy',
    description: 'Health, wellness & personal care',
    icon: 'pill',
    color: 'rose',
    isDefault: false,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'list_farmers',
    name: 'Farmers Market',
    description: 'Organic weekend market favorites',
    icon: 'carrot',
    color: 'cyan',
    isDefault: false,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
];

export const INITIAL_ITEMS: GroceryItem[] = [
  // Supermarket
  {
    id: 'item_1',
    listId: 'list_supermarket',
    name: 'Organic Honeycrisp Apples',
    quantity: 6,
    unit: 'pcs',
    category: 'Produce',
    note: 'Crisp & sweet for snacking',
    completed: false,
    completedAt: null,
    completedBy: null,
    addedBy: {
      deviceId: 'dev_kitchen_ipad',
      deviceName: 'Kitchen iPad',
      color: '#10b981',
    },
    createdAt: Date.now() - 3600000 * 5,
    updatedAt: Date.now() - 3600000 * 5,
  },
  {
    id: 'item_2',
    listId: 'list_supermarket',
    name: 'Oat Milk Barista Edition',
    quantity: 2,
    unit: 'cartons',
    category: 'Dairy & Eggs',
    note: 'For morning latte',
    completed: false,
    completedAt: null,
    completedBy: null,
    addedBy: {
      deviceId: 'dev_dad_phone',
      deviceName: 'Dad Phone',
      color: '#3b82f6',
    },
    createdAt: Date.now() - 3600000 * 4,
    updatedAt: Date.now() - 3600000 * 4,
  },
  {
    id: 'item_3',
    listId: 'list_supermarket',
    name: 'Artisan Sourdough Loaf',
    quantity: 1,
    unit: 'loaf',
    category: 'Bakery',
    note: 'Freshly baked',
    completed: false,
    completedAt: null,
    completedBy: null,
    addedBy: {
      deviceId: 'dev_kitchen_ipad',
      deviceName: 'Kitchen iPad',
      color: '#10b981',
    },
    createdAt: Date.now() - 3600000 * 3,
    updatedAt: Date.now() - 3600000 * 3,
  },
  {
    id: 'item_4',
    listId: 'list_supermarket',
    name: 'Hass Avocados',
    quantity: 4,
    unit: 'pcs',
    category: 'Produce',
    note: 'Slightly soft to touch',
    completed: true,
    completedAt: Date.now() - 1800000,
    completedBy: {
      deviceId: 'dev_dad_phone',
      deviceName: 'Dad Phone',
      color: '#3b82f6',
    },
    addedBy: {
      deviceId: 'dev_dad_phone',
      deviceName: 'Dad Phone',
      color: '#3b82f6',
    },
    createdAt: Date.now() - 3600000 * 6,
    updatedAt: Date.now() - 1800000,
  },
  {
    id: 'item_5',
    listId: 'list_supermarket',
    name: 'Free-Range Brown Eggs',
    quantity: 12,
    unit: 'pack',
    category: 'Dairy & Eggs',
    note: 'Large carton',
    completed: true,
    completedAt: Date.now() - 2400000,
    completedBy: {
      deviceId: 'dev_kitchen_ipad',
      deviceName: 'Kitchen iPad',
      color: '#10b981',
    },
    addedBy: {
      deviceId: 'dev_kitchen_ipad',
      deviceName: 'Kitchen iPad',
      color: '#10b981',
    },
    createdAt: Date.now() - 3600000 * 7,
    updatedAt: Date.now() - 2400000,
  },

  // Costco
  {
    id: 'item_c1',
    listId: 'list_costco',
    name: 'Paper Towels (12 Rolls)',
    quantity: 1,
    unit: 'pack',
    category: 'Household & Cleaning',
    note: 'Kirkland signature',
    completed: false,
    completedAt: null,
    completedBy: null,
    addedBy: {
      deviceId: 'dev_dad_phone',
      deviceName: 'Dad Phone',
      color: '#3b82f6',
    },
    createdAt: Date.now() - 3600000 * 12,
    updatedAt: Date.now() - 3600000 * 12,
  },
  {
    id: 'item_c2',
    listId: 'list_costco',
    name: 'Sparkling Mineral Water (24pk)',
    quantity: 2,
    unit: 'boxes',
    category: 'Beverages',
    note: 'Lime or Grapefruit',
    completed: false,
    completedAt: null,
    completedBy: null,
    addedBy: {
      deviceId: 'dev_kitchen_ipad',
      deviceName: 'Kitchen iPad',
      color: '#10b981',
    },
    createdAt: Date.now() - 3600000 * 10,
    updatedAt: Date.now() - 3600000 * 10,
  },

  // Pharmacy
  {
    id: 'item_p1',
    listId: 'list_pharmacy',
    name: 'Vitamin D3 2000 IU',
    quantity: 1,
    unit: 'bottle',
    category: 'Pharmacy & Health',
    note: 'Softgels',
    completed: false,
    completedAt: null,
    completedBy: null,
    addedBy: {
      deviceId: 'dev_dad_phone',
      deviceName: 'Dad Phone',
      color: '#3b82f6',
    },
    createdAt: Date.now() - 3600000 * 20,
    updatedAt: Date.now() - 3600000 * 20,
  },
  {
    id: 'item_p2',
    listId: 'list_pharmacy',
    name: 'Hydrocolloid Band-Aids',
    quantity: 1,
    unit: 'box',
    category: 'Pharmacy & Health',
    note: 'Waterproof',
    completed: false,
    completedAt: null,
    completedBy: null,
    addedBy: {
      deviceId: 'dev_kitchen_ipad',
      deviceName: 'Kitchen iPad',
      color: '#10b981',
    },
    createdAt: Date.now() - 3600000 * 18,
    updatedAt: Date.now() - 3600000 * 18,
  },
];
